# GENERATED by scripts/gen_models.py from schema/openapi.json. Do not edit.

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class Role(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class AcceptInviteOut(BaseModel):
    customer_id: str = Field(..., title='Customer Id')
    role: Role = Field(..., title='Role')


class ArtifactCreate(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    span_id: UUID | None = Field(None, title='Span Id')
    step_index: int | None = Field(None, title='Step Index')
    uri: str | None = Field(None, title='Uri')


class ArtifactOut(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    experiment_id: UUID | None = Field(None, title='Experiment Id')
    id: UUID = Field(..., title='Id')
    is_reference: bool = Field(..., title='Is Reference')
    kind: str = Field(..., title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    run_id: UUID | None = Field(None, title='Run Id')
    size_bytes: int | None = Field(None, title='Size Bytes')
    span_id: UUID | None = Field(None, title='Span Id')
    step_index: int | None = Field(None, title='Step Index')
    uri: str | None = Field(None, title='Uri')


class ExperimentArtifactCreate(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    uri: str | None = Field(None, title='Uri')


class ExperimentCreate(BaseModel):
    description: str | None = Field(None, title='Description')
    hypothesis: str = Field(..., min_length=1, title='Hypothesis')
    name: str = Field(..., title='Name')
    project_id: UUID | None = Field(None, title='Project Id')
    slug: str = Field(..., title='Slug')
    tags: list[str] | None = Field(None, title='Tags')


class ExperimentOut(BaseModel):
    archived_at: AwareDatetime | None = Field(None, title='Archived At')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    description: str | None = Field(None, title='Description')
    hypothesis: str = Field(..., title='Hypothesis')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    project_id: UUID = Field(..., title='Project Id')
    slug: str = Field(..., title='Slug')
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class Hypothesis(RootModel[str]):
    root: str = Field(..., min_length=1, title='Hypothesis')


class Name(RootModel[str]):
    root: str = Field(..., min_length=1, title='Name')


class ExperimentPatch(BaseModel):
    """
    Field-replace PATCH (D9). Only provided fields change; None = untouched.
    `hypothesis`/`name` carry min_length=1 so a PATCH can never re-blank them.
    """

    description: str | None = Field(None, title='Description')
    hypothesis: Hypothesis | None = Field(None, title='Hypothesis')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: Name | None = Field(None, title='Name')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class IngestArtifact(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    external_span_key: str | None = Field(None, title='External Span Key')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    step_index: int | None = Field(None, title='Step Index')
    uri: str | None = Field(None, title='Uri')


class Role1(StrEnum):
    admin = 'admin'
    member = 'member'


class InviteCreate(BaseModel):
    email: str = Field(
        ..., max_length=254, pattern='^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$', title='Email'
    )
    role: Role1 | None = Field('member', title='Role')


class InviteOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    email: str = Field(..., title='Email')
    id: UUID = Field(..., title='Id')
    role: Role1 = Field(..., title='Role')


class MetricInsertResult(BaseModel):
    inserted: int = Field(..., title='Inserted')


class MetricPointIn(BaseModel):
    key: str = Field(..., title='Key')
    kind: str | None = Field('model', title='Kind')
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime | None = Field(None, title='Wall Clock')


class MetricPointOut(BaseModel):
    id: int = Field(..., title='Id')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    run_id: UUID = Field(..., title='Run Id')
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime = Field(..., title='Wall Clock')


class MetricSeriesOut(BaseModel):
    """
    One catalog row: what/how-much/what-shape, no point scan (D15).
    """

    first_step_index: int | None = Field(None, title='First Step Index')
    first_wall_clock: AwareDatetime | None = Field(None, title='First Wall Clock')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    last_step_index: int | None = Field(None, title='Last Step Index')
    last_value: float | None = Field(None, title='Last Value')
    last_wall_clock: AwareDatetime | None = Field(None, title='Last Wall Clock')
    max_value: float | None = Field(None, title='Max Value')
    min_value: float | None = Field(None, title='Min Value')
    point_count: int = Field(..., title='Point Count')
    run_id: UUID = Field(..., title='Run Id')
    x_axis: str | None = Field('step', title='X Axis')


class ParentRelation(StrEnum):
    fork = 'fork'
    resume = 'resume'
    retry = 'retry'
    branch = 'branch'


class PendingInviteOut(BaseModel):
    """
    An invite shown to the invitee on /onboarding (joined to team name).
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    display_name: str = Field(..., title='Display Name')
    id: UUID = Field(..., title='Id')
    role: Role1 = Field(..., title='Role')


class ProjectCreate(BaseModel):
    description: str | None = Field(None, title='Description')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')


class ProjectOut(BaseModel):
    archived_at: AwareDatetime | None = Field(None, title='Archived At')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    description: str | None = Field(None, title='Description')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')


class ProjectPatch(BaseModel):
    """
    Field-replace PATCH (D9). Only provided fields change; None = untouched.
    """

    description: str | None = Field(None, title='Description')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: Name | None = Field(None, title='Name')


class RunCounts(BaseModel):
    """
    Child-row tallies nested under RunOut.counts (dashboard contract).
    """

    artifacts: int = Field(..., title='Artifacts')
    metrics: int = Field(..., title='Metrics')
    spans: int = Field(..., title='Spans')


class RunCreate(BaseModel):
    config: dict[str, Any] | None = Field(None, title='Config')
    external_id: str | None = Field(None, title='External Id')
    group_id: UUID | None = Field(None, title='Group Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_relation: ParentRelation | None = None
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    source: str | None = Field('api', title='Source')
    tags: list[str] | None = Field(None, title='Tags')


class RunIds(RootModel[list[UUID]]):
    root: list[UUID] = Field(..., max_length=50, title='Run Ids')


class RunGcRequest(BaseModel):
    """
    Permanently purge deleted runs (owner/admin). Exactly one selector: an
    explicit id list, or every run soft-deleted before `older_than`.
    """

    older_than: AwareDatetime | None = Field(None, title='Older Than')
    run_ids: RunIds | None = Field(None, title='Run Ids')


class RunGcResult(BaseModel):
    purged: int = Field(..., title='Purged')


class RunGroupCreate(BaseModel):
    kind: str | None = Field('group', title='Kind')
    name: str = Field(..., title='Name')
    spec: dict[str, Any] | None = Field(None, title='Spec')


class RunGroupOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    experiment_id: UUID = Field(..., title='Experiment Id')
    id: UUID = Field(..., title='Id')
    kind: str = Field(..., title='Kind')
    name: str = Field(..., title='Name')
    spec: dict[str, Any] | None = Field(None, title='Spec')


class RunGroupPatch(BaseModel):
    """
    Field-replace PATCH (D9). Only provided fields change; None = untouched.
    """

    name: Name | None = Field(None, title='Name')
    spec: dict[str, Any] | None = Field(None, title='Spec')


class RunStatus(StrEnum):
    created = 'created'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    crashed = 'crashed'
    canceled = 'canceled'


class Scope(StrEnum):
    """
    Coarse v1 authorization scopes (D2). Narrowable later; checked as explicit
    sets per route, NOT as a hierarchy (a `write` token does not imply `read`).
    """

    read = 'read'
    write = 'write'
    delete = 'delete'
    admin = 'admin'


class SeriesPoint(BaseModel):
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime = Field(..., title='Wall Clock')


class MaxPoints(RootModel[int]):
    root: int = Field(..., ge=2, le=100000, title='Max Points')


class SeriesResult(BaseModel):
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    points: list[SeriesPoint] = Field(..., title='Points')
    run_id: UUID = Field(..., title='Run Id')
    x_axis: str = Field(..., title='X Axis')


class SeriesSelector(BaseModel):
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')


class SpanCreate(BaseModel):
    attributes: dict[str, Any] | None = Field(None, title='Attributes')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    external_key: str | None = Field(None, title='External Key')
    id: UUID = Field(..., title='Id')
    name: str | None = Field(None, title='Name')
    parent_span_id: UUID | None = Field(None, title='Parent Span Id')
    provider: str | None = Field(None, title='Provider')
    span_type: str = Field(..., title='Span Type')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: str | None = Field('running', title='Status')
    step_index: int | None = Field(None, title='Step Index')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SpanOut(BaseModel):
    attributes: dict[str, Any] | None = Field(None, title='Attributes')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    external_key: str | None = Field(None, title='External Key')
    id: UUID = Field(..., title='Id')
    name: str | None = Field(None, title='Name')
    parent_span_id: UUID | None = Field(None, title='Parent Span Id')
    provider: str | None = Field(None, title='Provider')
    run_id: UUID = Field(..., title='Run Id')
    span_type: str = Field(..., title='Span Type')
    started_at: AwareDatetime = Field(..., title='Started At')
    status: str = Field(..., title='Status')
    step_index: int | None = Field(None, title='Step Index')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SpanTypeCount(BaseModel):
    count: int = Field(..., title='Count')
    span_type: str = Field(..., title='Span Type')


class SpanUpsertResult(BaseModel):
    """
    Typed replacement for the bare `{"upserted": n}` dict (D9).
    """

    upserted: int = Field(..., title='Upserted')


class StepCreate(BaseModel):
    attributes: dict[str, Any] | None = Field(None, title='Attributes')
    name: str | None = Field(None, title='Name')
    step_index: int = Field(..., title='Step Index')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SwitchTeamRequest(BaseModel):
    customer_id: str = Field(..., title='Customer Id')


class TeamCreate(BaseModel):
    """
    POST /auth/teams. `slug` format/uniqueness is validated
    server-side (app.provisioning) so the 400/409 carries a helpful message +
    a collision suggestion; the model only bounds length.
    """

    display_name: str = Field(..., max_length=120, min_length=1, title='Display Name')
    slug: str = Field(..., max_length=64, min_length=1, title='Slug')


class Role4(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class TeamMemberOut(BaseModel):
    """
    One active team membership joined to its human identity.
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    email: str = Field(..., title='Email')
    name: str | None = Field(None, title='Name')
    picture: str | None = Field(None, title='Picture')
    role: Role4 = Field(..., title='Role')
    user_id: UUID = Field(..., title='User Id')


class Role5(StrEnum):
    admin = 'admin'
    member = 'member'


class TeamMemberRoleUpdate(BaseModel):
    """
    Owner-controlled role change for an existing non-owner member.

    Ownership transfer is intentionally not part of the v1 management surface;
    a team always retains the owner created during provisioning.
    """

    role: Role5 = Field(..., title='Role')


class Role6(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class TeamOut(BaseModel):
    customer_id: str = Field(..., title='Customer Id')
    display_name: str | None = Field(None, title='Display Name')
    role: Role6 = Field(..., title='Role')


class TokenCreate(BaseModel):
    """
    POST /v1/tokens (session-only mint). `scopes=None` inherits the caller's
    role; e.g. `['read']` mints a read-only 'notebook' token. `expires_at=None`
    means non-expiring (house precedent).
    """

    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    name: str = Field(..., max_length=120, min_length=1, title='Name')
    scopes: list[Scope] | None = Field(None, title='Scopes')


class TokenCreated(BaseModel):
    """
    Mint response — carries the plaintext secret ONCE (never stored, never
    shown again).
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    id: UUID = Field(..., title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    name: str = Field(..., title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    token: str = Field(..., title='Token')
    token_prefix: str = Field(..., title='Token Prefix')


class TokenOut(BaseModel):
    """
    A token as listed (never carries the secret).
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    id: UUID = Field(..., title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    name: str = Field(..., title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    token_prefix: str = Field(..., title='Token Prefix')


class ValidationError(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class IngestRun(BaseModel):
    config: dict[str, Any] | None = Field(None, title='Config')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    external_id: str = Field(..., title='External Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_external_id: str | None = Field(None, title='Parent External Id')
    parent_relation: ParentRelation | None = None
    source: str | None = Field('api', title='Source')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: RunStatus | None = 'running'
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class IngestRunRequest(BaseModel):
    artifacts: list[IngestArtifact] | None = Field(
        None, max_length=1000, title='Artifacts'
    )
    batch_id: str | None = Field(None, title='Batch Id')
    experiment_hypothesis: str | None = Field(None, title='Experiment Hypothesis')
    experiment_slug: str = Field(..., title='Experiment Slug')
    metrics: list[MetricPointIn] | None = Field(None, max_length=50000, title='Metrics')
    project_slug: str | None = Field(None, title='Project Slug')
    run: IngestRun
    spans: list[SpanCreate] | None = Field(None, max_length=10000, title='Spans')


class MetricBatch(BaseModel):
    points: list[MetricPointIn] = Field(..., max_length=50000, title='Points')


class RunOut(BaseModel):
    config: dict[str, Any] | None = Field(None, title='Config')
    counts: RunCounts | None = None
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    deleted_at: AwareDatetime | None = Field(None, title='Deleted At')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    experiment_id: UUID = Field(..., title='Experiment Id')
    external_id: str | None = Field(None, title='External Id')
    group_id: UUID | None = Field(None, title='Group Id')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_relation: ParentRelation | None = None
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    source: str = Field(..., title='Source')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: RunStatus
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class RunPatch(BaseModel):
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: Name | None = Field(None, title='Name')
    status: RunStatus | None = None
    summary: dict[str, Any] | None = Field(None, title='Summary')


class Series(RootModel[list[SeriesSelector]]):
    root: list[SeriesSelector] = Field(..., max_length=200, title='Series')


class SeriesQueryRequest(BaseModel):
    """
    Multi-run, multi-series read for the run page AND N-run comparison (D9).
    """

    max_points: MaxPoints | None = Field(None, title='Max Points')
    run_ids: list[UUID] = Field(..., max_length=50, min_length=1, title='Run Ids')
    series: Series | None = Field(None, title='Series')
    step_from: int | None = Field(None, title='Step From')
    step_to: int | None = Field(None, title='Step To')


class SeriesQueryResult(BaseModel):
    series: list[SeriesResult] = Field(..., title='Series')


class SpanBatch(BaseModel):
    spans: list[SpanCreate] = Field(..., max_length=10000, title='Spans')


class RunBundle(BaseModel):
    """
    One request: run + catalog + artifact index (bounded) + spans overview +
    lineage refs. Raw points are excluded (fetch via /series/query).
    """

    artifact_total: int = Field(..., title='Artifact Total')
    artifacts: list[ArtifactOut] = Field(..., title='Artifacts')
    child_run_ids: list[UUID] | None = Field(None, title='Child Run Ids')
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    run: RunOut
    series: list[MetricSeriesOut] = Field(..., title='Series')
    span_types: list[SpanTypeCount] = Field(..., title='Span Types')


class RunLineage(BaseModel):
    """
    Ancestors + descendants of a run (recursive-CTE result).
    """

    ancestors: list[RunOut] | None = Field(None, title='Ancestors')
    descendants: list[RunOut] | None = Field(None, title='Descendants')
    run_id: UUID = Field(..., title='Run Id')
