# GENERATED by scripts/gen_models.py from schema/openapi.json. Do not edit.

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Role(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class AcceptInviteOut(BaseModel):
    customer_id: str = Field(..., title='Customer Id')
    role: Role = Field(..., title='Role')


class ArtifactCreate(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    span_id: UUID | None = Field(None, title='Span Id')
    step_index: int | None = Field(None, title='Step Index')
    uri: str | None = Field(None, title='Uri')


class ArtifactOut(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    experiment_id: UUID | None = Field(None, title='Experiment Id')
    id: UUID = Field(..., title='Id')
    is_reference: bool = Field(..., title='Is Reference')
    kind: str = Field(..., title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    project_id: UUID | None = Field(None, title='Project Id')
    run_id: UUID | None = Field(None, title='Run Id')
    size_bytes: int | None = Field(None, title='Size Bytes')
    span_id: UUID | None = Field(None, title='Span Id')
    status: str | None = Field('complete', title='Status')
    step_index: int | None = Field(None, title='Step Index')
    uri: str | None = Field(None, title='Uri')


class AssetCreate(BaseModel):
    description: str | None = Field(None, title='Description')
    kind: str | None = Field('dataset', title='Kind')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., min_length=1, title='Name')
    tags: list[str] | None = Field(None, title='Tags')


class AssetOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    description: str | None = Field(None, title='Description')
    id: UUID = Field(..., title='Id')
    kind: str = Field(..., title='Kind')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    tags: list[str] | None = Field(None, title='Tags')


class AssetVersionCreate(BaseModel):
    """
    Create a version. Either PROMOTE from an existing artifact (`from_artifact_id`,
    zero-copy: the version copies the artifact's content_hash + full r2:// uri + size)
    OR supply the pointer identity directly.
    """

    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    from_artifact_id: UUID | None = Field(None, title='From Artifact Id')
    label: str | None = Field(None, title='Label')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    size_bytes: int | None = Field(None, title='Size Bytes')
    uri: str | None = Field(None, title='Uri')


class AssetVersionOut(BaseModel):
    asset_id: UUID = Field(..., title='Asset Id')
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    id: UUID = Field(..., title='Id')
    label: str | None = Field(None, title='Label')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    size_bytes: int | None = Field(None, title='Size Bytes')
    source_artifact_id: UUID | None = Field(None, title='Source Artifact Id')
    uri: str | None = Field(None, title='Uri')
    version: int = Field(..., title='Version')


class BodyConsentOauthConsentPost(BaseModel):
    csrf: str = Field(..., title='Csrf')
    decision: str = Field(..., title='Decision')


class BodyTokenOauthTokenPost(BaseModel):
    client_id: str | None = Field(None, title='Client Id')
    code: str | None = Field(None, title='Code')
    code_verifier: str | None = Field(None, title='Code Verifier')
    grant_type: str = Field(..., title='Grant Type')
    redirect_uri: str | None = Field(None, title='Redirect Uri')
    refresh_token: str | None = Field(None, title='Refresh Token')


class ClientRegistrationIn(BaseModel):
    """
    RFC 7591 dynamic client registration request. We accept the standard
    metadata but fix grant/response types and the (none) auth method ourselves.
    """

    client_name: str | None = Field(None, title='Client Name')
    grant_types: list[str] | None = Field(None, title='Grant Types')
    redirect_uris: list[str] = Field(..., min_length=1, title='Redirect Uris')
    response_types: list[str] | None = Field(None, title='Response Types')
    scope: str | None = Field(None, title='Scope')
    token_endpoint_auth_method: str | None = Field(
        None, title='Token Endpoint Auth Method'
    )


class Decision(StrEnum):
    approve = 'approve'
    deny = 'deny'


class DeviceAuthorizationDecision(BaseModel):
    decision: Decision = Field(..., title='Decision')


class Status(StrEnum):
    approved = 'approved'
    denied = 'denied'


class DeviceAuthorizationDecisionOut(BaseModel):
    status: Status = Field(..., title='Status')


class Status1(StrEnum):
    pending = 'pending'
    approved = 'approved'
    denied = 'denied'
    expired = 'expired'
    consumed = 'consumed'


class DeviceAuthorizationOut(BaseModel):
    client_name: str = Field(..., title='Client Name')
    expires_at: AwareDatetime = Field(..., title='Expires At')
    scopes: list[str] | None = Field(None, title='Scopes')
    status: Status1 = Field(..., title='Status')
    token_name: str = Field(..., title='Token Name')
    user_code: str = Field(..., title='User Code')


class DeviceAuthorizationStartOut(BaseModel):
    device_code: str = Field(..., title='Device Code')
    expires_in: int = Field(..., title='Expires In')
    interval: int = Field(..., title='Interval')
    user_code: str = Field(..., title='User Code')
    verification_uri: str = Field(..., title='Verification Uri')
    verification_uri_complete: str = Field(..., title='Verification Uri Complete')


class DeviceTokenCreated(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    id: UUID = Field(..., title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    name: str = Field(..., title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    token: str = Field(..., title='Token')
    token_prefix: str = Field(..., title='Token Prefix')
    token_type: Literal['Bearer'] = Field('Bearer', title='Token Type')


class DeviceTokenExchange(BaseModel):
    code_verifier: str = Field(
        ...,
        max_length=128,
        min_length=43,
        pattern='^[A-Za-z0-9._~-]+$',
        title='Code Verifier',
    )
    device_code: str = Field(..., max_length=256, min_length=32, title='Device Code')


class DownloadResponse(BaseModel):
    download_url: str = Field(..., title='Download Url')


class EventOut(BaseModel):
    actor: str | None = Field(None, title='Actor')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    event_type: str = Field(..., title='Event Type')
    id: UUID = Field(..., title='Id')
    payload: dict[str, Any] | None = Field(None, title='Payload')
    subject_id: UUID | None = Field(None, title='Subject Id')
    subject_type: str | None = Field(None, title='Subject Type')


class ExecutionRecordCreate(BaseModel):
    code: dict[str, Any] | None = Field(None, title='Code')
    deps: dict[str, Any] | None = Field(None, title='Deps')
    hardware: dict[str, Any] | None = Field(None, title='Hardware')
    paths: dict[str, Any] | None = Field(None, title='Paths')
    settings: dict[str, Any] | None = Field(None, title='Settings')


class ExecutionRecordOut(BaseModel):
    code: dict[str, Any] | None = Field(None, title='Code')
    content_hash: str = Field(..., title='Content Hash')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    deps: dict[str, Any] | None = Field(None, title='Deps')
    hardware: dict[str, Any] | None = Field(None, title='Hardware')
    paths: dict[str, Any] | None = Field(None, title='Paths')
    settings: dict[str, Any] | None = Field(None, title='Settings')


class ExperimentArtifactCreate(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    uri: str | None = Field(None, title='Uri')


class ExperimentCreate(BaseModel):
    description: str | None = Field(None, title='Description')
    hypothesis: str = Field(..., min_length=1, title='Hypothesis')
    name: str = Field(..., title='Name')
    project_id: UUID | None = Field(None, title='Project Id')
    slug: str = Field(..., title='Slug')
    tags: list[str] | None = Field(None, title='Tags')


class ExperimentOut(BaseModel):
    archived_at: AwareDatetime | None = Field(None, title='Archived At')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    description: str | None = Field(None, title='Description')
    hypothesis: str = Field(..., title='Hypothesis')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    project_id: UUID = Field(..., title='Project Id')
    slug: str = Field(..., title='Slug')
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class Hypothesis(RootModel[str]):
    root: str = Field(..., min_length=1, title='Hypothesis')


class Name(RootModel[str]):
    root: str = Field(..., min_length=1, title='Name')


class ExperimentPatch(BaseModel):
    """
    Field-replace PATCH (D9). Only provided fields change; None = untouched.
    `hypothesis`/`name` carry min_length=1 so a PATCH can never re-blank them.
    """

    description: str | None = Field(None, title='Description')
    hypothesis: Hypothesis | None = Field(None, title='Hypothesis')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: Name | None = Field(None, title='Name')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class ExperimentVersionMint(BaseModel):
    """
    Mint an immutable reproduction manifest (fold #6). `as_of` defaults to the
    mint-time watermark; `exclude_run_ids` are recorded and left out of the refs.
    """

    as_of: AwareDatetime | None = Field(None, title='As Of')
    exclude_run_ids: list[UUID] | None = Field(None, title='Exclude Run Ids')
    label: str | None = Field(None, title='Label')
    meta: dict[str, Any] | None = Field(None, title='Meta')


class ExperimentVersionOut(BaseModel):
    artifact_refs: list[UUID] | None = Field(None, title='Artifact Refs')
    as_of: AwareDatetime = Field(..., title='As Of')
    asset_version_refs: list[UUID] | None = Field(None, title='Asset Version Refs')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    excludes: dict[str, Any] | None = Field(None, title='Excludes')
    execution_record_refs: list[str] | None = Field(None, title='Execution Record Refs')
    experiment_id: UUID = Field(..., title='Experiment Id')
    id: UUID = Field(..., title='Id')
    label: str | None = Field(None, title='Label')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    run_refs: list[UUID] | None = Field(None, title='Run Refs')
    version: int = Field(..., title='Version')


class IngestArtifact(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    external_span_key: str | None = Field(None, title='External Span Key')
    external_span_type: str | None = Field(None, title='External Span Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    step_index: int | None = Field(None, title='Step Index')
    uri: str | None = Field(None, title='Uri')


class Role1(StrEnum):
    admin = 'admin'
    member = 'member'


class InviteCreate(BaseModel):
    email: str = Field(
        ..., max_length=254, pattern='^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$', title='Email'
    )
    role: Role1 | None = Field('member', title='Role')


class InviteOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    email: str = Field(..., title='Email')
    id: UUID = Field(..., title='Id')
    role: Role1 = Field(..., title='Role')


class LineageEdgeOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    id: UUID = Field(..., title='Id')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    relation: str = Field(..., title='Relation')
    source_id: UUID = Field(..., title='Source Id')
    source_type: str = Field(..., title='Source Type')
    target_id: UUID = Field(..., title='Target Id')
    target_type: str = Field(..., title='Target Type')


class LineageEntityType(StrEnum):
    """
    The endpoints a lineage edge can connect (closed set).
    """

    run = 'run'
    artifact = 'artifact'
    asset_version = 'asset_version'


class LineageRelation(StrEnum):
    """
    The closed relation vocabulary.
    """

    consumes = 'consumes'
    produces = 'produces'
    evaluates_on = 'evaluates_on'
    forked_from = 'forked_from'
    resumed_from = 'resumed_from'
    promoted_to = 'promoted_to'
    derived_from = 'derived_from'


class MetricInsertResult(BaseModel):
    inserted: int = Field(..., title='Inserted')


class MetricPointIn(BaseModel):
    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    key: str = Field(..., title='Key')
    kind: str | None = Field('model', title='Kind')
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime | None = Field(None, title='Wall Clock')


class MetricPointOut(BaseModel):
    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    id: int = Field(..., title='Id')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    run_id: UUID = Field(..., title='Run Id')
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime = Field(..., title='Wall Clock')


class MetricSeriesOut(BaseModel):
    """
    One catalog row: what/how-much/what-shape, no point scan (D15).
    """

    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    first_step_index: int | None = Field(None, title='First Step Index')
    first_wall_clock: AwareDatetime | None = Field(None, title='First Wall Clock')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    last_step_index: int | None = Field(None, title='Last Step Index')
    last_value: float | None = Field(None, title='Last Value')
    last_wall_clock: AwareDatetime | None = Field(None, title='Last Wall Clock')
    max_value: float | None = Field(None, title='Max Value')
    min_value: float | None = Field(None, title='Min Value')
    point_count: int = Field(..., title='Point Count')
    run_id: UUID = Field(..., title='Run Id')
    x_axis: str | None = Field('step', title='X Axis')


class ParentRelation(StrEnum):
    fork = 'fork'
    resume = 'resume'
    retry = 'retry'
    branch = 'branch'


class PendingInviteOut(BaseModel):
    """
    An invite shown to the invitee on /onboarding (joined to team name).
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    display_name: str = Field(..., title='Display Name')
    id: UUID = Field(..., title='Id')
    role: Role1 = Field(..., title='Role')


class ProjectArtifactCreate(BaseModel):
    """
    Project-anchored artifact (fold #22); same shape as the experiment-anchored one.
    """

    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    uri: str | None = Field(None, title='Uri')


class ProjectCreate(BaseModel):
    description: str | None = Field(None, title='Description')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')


class ProjectOut(BaseModel):
    archived_at: AwareDatetime | None = Field(None, title='Archived At')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    description: str | None = Field(None, title='Description')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')


class ProjectPatch(BaseModel):
    """
    Field-replace PATCH (D9). Only provided fields change; None = untouched.
    """

    description: str | None = Field(None, title='Description')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: Name | None = Field(None, title='Name')


class RunCounts(BaseModel):
    """
    Child-row tallies nested under RunOut.counts (dashboard contract).
    """

    artifacts: int = Field(..., title='Artifacts')
    metrics: int = Field(..., title='Metrics')
    spans: int = Field(..., title='Spans')


class RunCreate(BaseModel):
    config: dict[str, Any] | None = Field(None, title='Config')
    env_ref: str | None = Field(None, title='Env Ref')
    external_id: str | None = Field(None, title='External Id')
    foreign_keys: dict[str, Any] | None = Field(None, title='Foreign Keys')
    group_id: UUID | None = Field(None, title='Group Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_relation: ParentRelation | None = None
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    source: str | None = Field('api', title='Source')
    tags: list[str] | None = Field(None, title='Tags')


class RunIds(RootModel[list[UUID]]):
    root: list[UUID] = Field(..., max_length=50, title='Run Ids')


class RunGcRequest(BaseModel):
    """
    Permanently purge deleted runs (owner/admin). Exactly one selector: an
    explicit id list, or every run soft-deleted before `older_than`.
    """

    older_than: AwareDatetime | None = Field(None, title='Older Than')
    run_ids: RunIds | None = Field(None, title='Run Ids')


class RunGcResult(BaseModel):
    purged: int = Field(..., title='Purged')


class RunGroupCreate(BaseModel):
    kind: str | None = Field('group', title='Kind')
    name: str = Field(..., title='Name')
    spec: dict[str, Any] | None = Field(None, title='Spec')


class RunGroupOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    experiment_id: UUID = Field(..., title='Experiment Id')
    id: UUID = Field(..., title='Id')
    kind: str = Field(..., title='Kind')
    name: str = Field(..., title='Name')
    spec: dict[str, Any] | None = Field(None, title='Spec')


class RunGroupPatch(BaseModel):
    """
    Field-replace PATCH (D9). Only provided fields change; None = untouched.
    """

    name: Name | None = Field(None, title='Name')
    spec: dict[str, Any] | None = Field(None, title='Spec')


class RunStatus(StrEnum):
    created = 'created'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    crashed = 'crashed'
    canceled = 'canceled'


class Scope(StrEnum):
    """
    Coarse v1 authorization scopes (D2). Narrowable later; checked as explicit
    sets per route, NOT as a hierarchy (a `write` token does not imply `read`).
    """

    read = 'read'
    write = 'write'
    delete = 'delete'
    admin = 'admin'


class ScopedUploadRequest(BaseModel):
    """
    Upload fields shared by project and experiment anchors.

    The anchor comes exclusively from the URL and the R2 pointer/key are always
    server-built. Forbid extras so a client-supplied ``uri`` or ``key`` is rejected
    instead of being silently ignored by Pydantic.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    content_hash: str = Field(..., title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')


class SeriesPoint(BaseModel):
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime = Field(..., title='Wall Clock')


class MaxPoints(RootModel[int]):
    root: int = Field(..., ge=2, le=100000, title='Max Points')


class SeriesResult(BaseModel):
    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    points: list[SeriesPoint] = Field(..., title='Points')
    run_id: UUID = Field(..., title='Run Id')
    x_axis: str = Field(..., title='X Axis')


class SeriesSelector(BaseModel):
    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')


class SpanCreate(BaseModel):
    attributes: dict[str, Any] | None = Field(None, title='Attributes')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    env_ref: str | None = Field(None, title='Env Ref')
    external_key: str | None = Field(None, title='External Key')
    id: UUID = Field(..., title='Id')
    name: str | None = Field(None, title='Name')
    parent_span_id: UUID | None = Field(None, title='Parent Span Id')
    provider: str | None = Field(None, title='Provider')
    span_type: str = Field(..., title='Span Type')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: str | None = Field('running', title='Status')
    step_index: int | None = Field(None, title='Step Index')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SpanOut(BaseModel):
    attributes: dict[str, Any] | None = Field(None, title='Attributes')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    external_key: str | None = Field(None, title='External Key')
    id: UUID = Field(..., title='Id')
    name: str | None = Field(None, title='Name')
    parent_span_id: UUID | None = Field(None, title='Parent Span Id')
    provider: str | None = Field(None, title='Provider')
    run_id: UUID = Field(..., title='Run Id')
    span_type: str = Field(..., title='Span Type')
    started_at: AwareDatetime = Field(..., title='Started At')
    status: str = Field(..., title='Status')
    step_index: int | None = Field(None, title='Step Index')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SpanTypeCount(BaseModel):
    count: int = Field(..., title='Count')
    span_type: str = Field(..., title='Span Type')


class SpanUpsertResult(BaseModel):
    """
    Typed replacement for the bare `{"upserted": n}` dict (D9).
    """

    upserted: int = Field(..., title='Upserted')


class StepCreate(BaseModel):
    attributes: dict[str, Any] | None = Field(None, title='Attributes')
    name: str | None = Field(None, title='Name')
    step_index: int = Field(..., title='Step Index')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SwitchTeamRequest(BaseModel):
    customer_id: str = Field(..., title='Customer Id')


class TeamCreate(BaseModel):
    """
    POST /auth/teams. `slug` format/uniqueness is validated
    server-side (app.teams.service) so the 400/409 carries a helpful message +
    a collision suggestion; the model only bounds length.
    """

    display_name: str = Field(..., max_length=120, min_length=1, title='Display Name')
    slug: str = Field(..., max_length=64, min_length=1, title='Slug')


class Role4(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class TeamMemberOut(BaseModel):
    """
    One active team membership joined to its human identity.
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    email: str = Field(..., title='Email')
    name: str | None = Field(None, title='Name')
    picture: str | None = Field(None, title='Picture')
    role: Role4 = Field(..., title='Role')
    user_id: UUID = Field(..., title='User Id')


class Role5(StrEnum):
    admin = 'admin'
    member = 'member'


class TeamMemberRoleUpdate(BaseModel):
    """
    Owner-controlled role change for an existing non-owner member.

    Ownership transfer is intentionally not part of the v1 management surface;
    a team always retains the owner created during provisioning.
    """

    role: Role5 = Field(..., title='Role')


class Role6(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class TeamOut(BaseModel):
    customer_id: str = Field(..., title='Customer Id')
    display_name: str | None = Field(None, title='Display Name')
    role: Role6 = Field(..., title='Role')


class TokenCreate(BaseModel):
    """
    POST /v1/tokens (session-only mint). `scopes=None` inherits the caller's
    role; e.g. `['read']` mints a read-only 'notebook' token. `expires_at=None`
    means non-expiring (house precedent).
    """

    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    name: str = Field(..., max_length=120, min_length=1, title='Name')
    scopes: list[Scope] | None = Field(None, title='Scopes')


class TokenCreated(BaseModel):
    """
    Mint response — carries the plaintext secret ONCE (never stored, never
    shown again).
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    id: UUID = Field(..., title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    name: str = Field(..., title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    token: str = Field(..., title='Token')
    token_prefix: str = Field(..., title='Token Prefix')


class TokenOut(BaseModel):
    """
    A token as listed (never carries the secret).
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    id: UUID = Field(..., title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    name: str = Field(..., title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    token_prefix: str = Field(..., title='Token Prefix')


class UploadGcRequest(BaseModel):
    older_than: AwareDatetime = Field(..., title='Older Than')


class UploadGcResult(BaseModel):
    swept: int = Field(..., title='Swept')


class UploadRequest(BaseModel):
    content_hash: str = Field(..., title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    kind: str | None = Field(None, title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    span_id: UUID | None = Field(None, title='Span Id')
    step_index: int | None = Field(None, title='Step Index')


class UploadResponse(BaseModel):
    artifact_id: UUID = Field(..., title='Artifact Id')
    have: bool = Field(..., title='Have')
    key: str | None = Field(None, title='Key')
    upload_headers: dict[str, str] | None = Field(None, title='Upload Headers')
    upload_url: str | None = Field(None, title='Upload Url')


class ValidationError(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class Scopes(RootModel[list[Scope]]):
    root: list[Scope] = Field(..., min_length=1, title='Scopes')


class DeviceAuthorizationStart(BaseModel):
    """
    Start a first-party CLI browser handoff.

    PKCE is mandatory even though the high-entropy device code is already a
    bearer secret: it binds the exchange to the CLI process that initiated it
    if a terminal transcript or launch URL is copied elsewhere.
    """

    code_challenge: str = Field(
        ..., pattern='^[A-Za-z0-9_-]{43}$', title='Code Challenge'
    )
    scopes: Scopes | None = Field(None, title='Scopes')
    token_name: str | None = Field(
        'Research OS CLI', max_length=120, min_length=1, title='Token Name'
    )


class EdgeCreate(BaseModel):
    meta: dict[str, Any] | None = Field(None, title='Meta')
    relation: LineageRelation
    source_id: UUID = Field(..., title='Source Id')
    source_type: LineageEntityType
    target_id: UUID = Field(..., title='Target Id')
    target_type: LineageEntityType


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class IngestRun(BaseModel):
    config: dict[str, Any] | None = Field(None, title='Config')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    external_id: str = Field(..., title='External Id')
    foreign_keys: dict[str, Any] | None = Field(None, title='Foreign Keys')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_external_id: str | None = Field(None, title='Parent External Id')
    parent_relation: ParentRelation | None = None
    source: str | None = Field('api', title='Source')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: RunStatus | None = 'running'
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class IngestRunRequest(BaseModel):
    artifacts: list[IngestArtifact] | None = Field(
        None, max_length=1000, title='Artifacts'
    )
    batch_id: str | None = Field(None, title='Batch Id')
    execution_record: ExecutionRecordCreate | None = None
    experiment_hypothesis: str | None = Field(None, title='Experiment Hypothesis')
    experiment_slug: str = Field(..., title='Experiment Slug')
    metrics: list[MetricPointIn] | None = Field(None, max_length=50000, title='Metrics')
    project_slug: str | None = Field(None, title='Project Slug')
    run: IngestRun
    spans: list[SpanCreate] | None = Field(None, max_length=10000, title='Spans')


class MetricBatch(BaseModel):
    points: list[MetricPointIn] = Field(..., max_length=50000, title='Points')


class RunDetailOut(BaseModel):
    """
    The /v1 read view of a run: RunOut plus the fold fields that are DELIBERATELY
    absent from RunOut so the frozen ingest response stays byte-identical (the ingest
    route keeps response_model=RunOut, which filters these out). short_id (fold #21)
    is the human-facing petname the dashboard displays; created_by (fold #1), env_ref
    (fold #7), and foreign_keys (fold #8) surface here for reads.
    """

    config: dict[str, Any] | None = Field(None, title='Config')
    counts: RunCounts | None = None
    created_at: AwareDatetime = Field(..., title='Created At')
    created_by: str | None = Field(None, title='Created By')
    customer_id: str = Field(..., title='Customer Id')
    deleted_at: AwareDatetime | None = Field(None, title='Deleted At')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    env_ref: str | None = Field(None, title='Env Ref')
    experiment_id: UUID = Field(..., title='Experiment Id')
    external_id: str | None = Field(None, title='External Id')
    foreign_keys: dict[str, Any] | None = Field(None, title='Foreign Keys')
    group_id: UUID | None = Field(None, title='Group Id')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_relation: ParentRelation | None = None
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    short_id: str | None = Field(None, title='Short Id')
    source: str = Field(..., title='Source')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: RunStatus
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class RunLineage(BaseModel):
    """
    Ancestors + descendants of a run (recursive-CTE result).
    """

    ancestors: list[RunDetailOut] | None = Field(None, title='Ancestors')
    descendants: list[RunDetailOut] | None = Field(None, title='Descendants')
    run_id: UUID = Field(..., title='Run Id')


class RunOut(BaseModel):
    config: dict[str, Any] | None = Field(None, title='Config')
    counts: RunCounts | None = None
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    deleted_at: AwareDatetime | None = Field(None, title='Deleted At')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    experiment_id: UUID = Field(..., title='Experiment Id')
    external_id: str | None = Field(None, title='External Id')
    group_id: UUID | None = Field(None, title='Group Id')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_relation: ParentRelation | None = None
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    source: str = Field(..., title='Source')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: RunStatus
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class RunPatch(BaseModel):
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    env_ref: str | None = Field(None, title='Env Ref')
    foreign_keys: dict[str, Any] | None = Field(None, title='Foreign Keys')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: Name | None = Field(None, title='Name')
    status: RunStatus | None = None
    summary: dict[str, Any] | None = Field(None, title='Summary')


class Series(RootModel[list[SeriesSelector]]):
    root: list[SeriesSelector] = Field(..., max_length=200, title='Series')


class SeriesQueryRequest(BaseModel):
    """
    Multi-run, multi-series read for the run page AND N-run comparison (D9).
    """

    max_points: MaxPoints | None = Field(None, title='Max Points')
    run_ids: list[UUID] = Field(..., max_length=50, min_length=1, title='Run Ids')
    series: Series | None = Field(None, title='Series')
    step_from: int | None = Field(None, title='Step From')
    step_to: int | None = Field(None, title='Step To')


class SeriesQueryResult(BaseModel):
    series: list[SeriesResult] = Field(..., title='Series')


class SpanBatch(BaseModel):
    spans: list[SpanCreate] = Field(..., max_length=10000, title='Spans')


class RunBundle(BaseModel):
    """
    One request: run + catalog + artifact index (bounded) + spans overview +
    lineage refs. Raw points are excluded (fetch via /series/query).
    """

    artifact_total: int = Field(..., title='Artifact Total')
    artifacts: list[ArtifactOut] = Field(..., title='Artifacts')
    child_run_ids: list[UUID] | None = Field(None, title='Child Run Ids')
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    run: RunDetailOut
    series: list[MetricSeriesOut] = Field(..., title='Series')
    span_types: list[SpanTypeCount] = Field(..., title='Span Types')
