# GENERATED by scripts/gen_models.py from schema/openapi.json. Do not edit.

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Role(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class AcceptInviteOut(BaseModel):
    customer_id: str = Field(..., title='Customer Id')
    role: Role = Field(..., title='Role')


class AnchorLevel(StrEnum):
    """
    The three vertically-movable artifact anchors (workspace/shared-folder files
    move via the share/unshare rails, not here). Ordered run < experiment < project
    so `move` can tell a promote (derive the target up the chain) from a demote
    (target_id required, and validated to sit inside the current subtree).
    """

    run = 'run'
    experiment = 'experiment'
    project = 'project'


class AnchorType(StrEnum):
    """
    What a summary (and a summary_refresh queue row) is about.

    Mirrors the `summary_refresh.anchor_type` CHECK constraint -- adding a member
    here without widening that CHECK makes every enqueue for it fail (silently,
    since `enqueue_summary_refresh` swallows to protect the domain write).
    """

    project = 'project'
    experiment = 'experiment'
    run = 'run'


class ArtifactCreate(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    span_id: UUID | None = Field(None, title='Span Id')
    step_index: int | None = Field(None, title='Step Index')
    uri: str | None = Field(None, title='Uri')


class ArtifactMove(BaseModel):
    """
    Move an artifact vertically along its own run->experiment->project chain.

    `target_id` is derived server-side for a promote (a run has exactly one
    experiment, an experiment one project) and REQUIRED for a demote (a parent has
    many children); a demote target is validated to sit inside the artifact's current
    subtree, so this can never express a lateral move to a sibling.
    """

    level: AnchorLevel
    target_id: UUID | None = Field(None, title='Target Id')


class ArtifactOut(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    experiment_id: UUID | None = Field(None, title='Experiment Id')
    id: UUID = Field(..., title='Id')
    is_reference: bool = Field(..., title='Is Reference')
    kind: str = Field(..., title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    path: str | None = Field('', title='Path')
    project_id: UUID | None = Field(None, title='Project Id')
    run_id: UUID | None = Field(None, title='Run Id')
    shared_folder_id: UUID | None = Field(None, title='Shared Folder Id')
    size_bytes: int | None = Field(None, title='Size Bytes')
    source_level: str | None = Field(None, title='Source Level')
    span_id: UUID | None = Field(None, title='Span Id')
    status: str | None = Field('complete', title='Status')
    step_index: int | None = Field(None, title='Step Index')
    uri: str | None = Field(None, title='Uri')
    workspace_id: UUID | None = Field(None, title='Workspace Id')


class ArtifactScope(StrEnum):
    """
    Which anchor levels a run's artifact listing spans.

    OWN (default) is the run's own artifacts only -- the historical behavior, so the
    run bundle, dashboard, and `artifact_count` are untouched. INHERITED and ALL are
    opt-in reads for the live-run/CLI case where a run needs to see what has been
    promoted to its experiment/project. Inheritance is resolution/listing on THIS
    endpoint only; it never widens the run's own count surfaces.
    """

    own = 'own'
    inherited = 'inherited'
    all = 'all'


class ArtifactVersionCreate(BaseModel):
    """
    Append a version. Either PROMOTE from an existing artifact (`from_artifact_id`,
    zero-copy: the version pins that artifact's content_hash + full r2:// uri + size)
    OR supply the pointer identity directly.
    """

    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    from_artifact_id: UUID | None = Field(None, title='From Artifact Id')
    label: str | None = Field(None, title='Label')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    size_bytes: int | None = Field(None, title='Size Bytes')
    uri: str | None = Field(None, title='Uri')


class ArtifactVersionOut(BaseModel):
    artifact_id: UUID = Field(..., title='Artifact Id')
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    created_at: AwareDatetime = Field(..., title='Created At')
    created_by: str | None = Field(None, title='Created By')
    customer_id: str = Field(..., title='Customer Id')
    deleted_at: AwareDatetime | None = Field(None, title='Deleted At')
    deleted_by: str | None = Field(None, title='Deleted By')
    id: UUID = Field(..., title='Id')
    label: str | None = Field(None, title='Label')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    origin: str = Field(..., title='Origin')
    size_bytes: int | None = Field(None, title='Size Bytes')
    source_artifact_id: UUID | None = Field(None, title='Source Artifact Id')
    status: str | None = Field('complete', title='Status')
    uri: str | None = Field(None, title='Uri')
    version: int = Field(..., title='Version')


class BodyConsentOauthConsentPost(BaseModel):
    csrf: str = Field(..., title='Csrf')
    decision: str = Field(..., title='Decision')


class BodyTokenOauthTokenPost(BaseModel):
    client_id: str | None = Field(None, title='Client Id')
    code: str | None = Field(None, title='Code')
    code_verifier: str | None = Field(None, title='Code Verifier')
    grant_type: str = Field(..., title='Grant Type')
    redirect_uri: str | None = Field(None, title='Redirect Uri')
    refresh_token: str | None = Field(None, title='Refresh Token')


class ChannelError(StrEnum):
    """
    Machine-readable per-channel failure reasons (state:"partial").
    """

    engine_unconfigured = 'engine_unconfigured'
    engine_timeout = 'engine_timeout'
    engine_error = 'engine_error'
    sql_budget_exceeded = 'sql_budget_exceeded'


class AutoUpdate(StrEnum):
    on = 'on'
    off = 'off'
    unknown = 'unknown'


class Mcp(StrEnum):
    installed = 'installed'
    absent = 'absent'
    unknown = 'unknown'


class Skills(StrEnum):
    installed = 'installed'
    absent = 'absent'
    unknown = 'unknown'


class ClientCapabilitiesIn(BaseModel):
    """
    The complete allowlisted local snapshot. Raw configuration is forbidden.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    auto_update: AutoUpdate = Field(..., title='Auto Update')
    mcp: Mcp = Field(..., title='Mcp')
    schema_version: Literal[1] = Field(..., title='Schema Version')
    skills: Skills = Field(..., title='Skills')


class ClientCapabilitiesOut(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    auto_update: AutoUpdate = Field(..., title='Auto Update')
    mcp: Mcp = Field(..., title='Mcp')
    reported_at: AwareDatetime = Field(..., title='Reported At')
    schema_version: Literal[1] = Field(..., title='Schema Version')
    skills: Skills = Field(..., title='Skills')


class ClientKind(StrEnum):
    """
    First-party clients that may report their installed version.
    """

    cli = 'cli'
    plugin = 'plugin'


class ClientRegistrationIn(BaseModel):
    """
    RFC 7591 dynamic client registration request. We accept the standard
    metadata but fix grant/response types and the (none) auth method ourselves.
    """

    client_name: str | None = Field(None, title='Client Name')
    grant_types: list[str] | None = Field(None, title='Grant Types')
    redirect_uris: list[str] = Field(..., min_length=1, title='Redirect Uris')
    response_types: list[str] | None = Field(None, title='Response Types')
    scope: str | None = Field(None, title='Scope')
    token_endpoint_auth_method: str | None = Field(
        None, title='Token Endpoint Auth Method'
    )


class ClientUpdateStatus(StrEnum):
    """
    How urgently one observed client should be updated.
    """

    update = 'update'
    required = 'required'


class CredentialAttachmentGrantOut(BaseModel):
    expires_at: AwareDatetime = Field(..., title='Expires At')
    grant: str = Field(..., title='Grant')


class CredentialAttachmentIn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    grant: str = Field(..., max_length=256, min_length=32, title='Grant')


class Role1(StrEnum):
    api = 'api'
    mcp = 'mcp'


class CredentialAttachmentOut(BaseModel):
    installation_id: UUID = Field(..., title='Installation Id')
    role: Role1 = Field(..., title='Role')
    token_id: UUID = Field(..., title='Token Id')


class Decision(StrEnum):
    approve = 'approve'
    deny = 'deny'


class DeviceAuthorizationDecision(BaseModel):
    decision: Decision = Field(..., title='Decision')


class Status(StrEnum):
    approved = 'approved'
    denied = 'denied'


class DeviceAuthorizationDecisionOut(BaseModel):
    status: Status = Field(..., title='Status')


class Status1(StrEnum):
    pending = 'pending'
    approved = 'approved'
    denied = 'denied'
    expired = 'expired'
    consumed = 'consumed'


class DeviceAuthorizationOut(BaseModel):
    client_name: str = Field(..., title='Client Name')
    expires_at: AwareDatetime = Field(..., title='Expires At')
    grants: list[str] | None = Field(None, title='Grants')
    scopes: list[str] | None = Field(None, title='Scopes')
    status: Status1 = Field(..., title='Status')
    token_name: str = Field(..., title='Token Name')
    user_code: str = Field(..., title='User Code')


class DeviceAuthorizationStartOut(BaseModel):
    device_code: str = Field(..., title='Device Code')
    expires_in: int = Field(..., title='Expires In')
    interval: int = Field(..., title='Interval')
    user_code: str = Field(..., title='User Code')
    verification_uri: str = Field(..., title='Verification Uri')
    verification_uri_complete: str = Field(..., title='Verification Uri Complete')


class DeviceTokenExchange(BaseModel):
    code_verifier: str = Field(
        ...,
        max_length=128,
        min_length=43,
        pattern='^[A-Za-z0-9._~-]+$',
        title='Code Verifier',
    )
    device_code: str = Field(..., max_length=256, min_length=32, title='Device Code')


class DownloadResponse(BaseModel):
    download_url: str = Field(..., title='Download Url')


class EventOut(BaseModel):
    actor: str | None = Field(None, title='Actor')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    event_type: str = Field(..., title='Event Type')
    id: UUID = Field(..., title='Id')
    payload: dict[str, Any] | None = Field(None, title='Payload')
    subject_id: UUID | None = Field(None, title='Subject Id')
    subject_type: str | None = Field(None, title='Subject Type')


class ExecutionRecordCreate(BaseModel):
    code: dict[str, Any] | None = Field(None, title='Code')
    deps: dict[str, Any] | None = Field(None, title='Deps')
    hardware: dict[str, Any] | None = Field(None, title='Hardware')
    paths: dict[str, Any] | None = Field(None, title='Paths')
    settings: dict[str, Any] | None = Field(None, title='Settings')


class ExecutionRecordOut(BaseModel):
    code: dict[str, Any] | None = Field(None, title='Code')
    content_hash: str = Field(..., title='Content Hash')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    deps: dict[str, Any] | None = Field(None, title='Deps')
    hardware: dict[str, Any] | None = Field(None, title='Hardware')
    paths: dict[str, Any] | None = Field(None, title='Paths')
    settings: dict[str, Any] | None = Field(None, title='Settings')


class ExperimentArtifactCreate(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    uri: str | None = Field(None, title='Uri')


class ExperimentCreate(BaseModel):
    description: str | None = Field(None, title='Description')
    hypothesis: str = Field(..., min_length=1, title='Hypothesis')
    name: str = Field(..., title='Name')
    project_id: UUID | None = Field(None, title='Project Id')
    slug: str = Field(..., title='Slug')
    tags: list[str] | None = Field(None, title='Tags')


class ExperimentOut(BaseModel):
    archived_at: AwareDatetime | None = Field(None, title='Archived At')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    description: str | None = Field(None, title='Description')
    hypothesis: str = Field(..., title='Hypothesis')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    project_id: UUID = Field(..., title='Project Id')
    slug: str = Field(..., title='Slug')
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class Hypothesis(RootModel[str]):
    root: str = Field(..., min_length=1, title='Hypothesis')


class Name(RootModel[str]):
    root: str = Field(..., min_length=1, title='Name')


class ExperimentPatch(BaseModel):
    """
    Field-replace PATCH (D9). Only provided fields change; None = untouched.
    `hypothesis`/`name` carry min_length=1 so a PATCH can never re-blank them.

    NO `summary` field, deliberately. An experiment summary is GENERATED -- it
    comes from the summary pipeline and lands in `metadata.summary`; there is no
    client-writable door to it. The field used to exist (documented as "the home
    for eval/benchmark aggregates"), but nothing in the CLI, SDK or ingest path
    ever wrote one, so all it did was let a client overwrite a generated
    document. Per-experiment aggregates belong on the runs that produced them.
    """

    description: str | None = Field(None, title='Description')
    hypothesis: Hypothesis | None = Field(None, title='Hypothesis')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: Name | None = Field(None, title='Name')


class ExperimentVersionMint(BaseModel):
    """
    Mint an immutable reproduction manifest (fold #6). `as_of` defaults to the
    mint-time watermark; `exclude_run_ids` are recorded and left out of the refs.
    """

    as_of: AwareDatetime | None = Field(None, title='As Of')
    exclude_run_ids: list[UUID] | None = Field(None, title='Exclude Run Ids')
    label: str | None = Field(None, title='Label')
    meta: dict[str, Any] | None = Field(None, title='Meta')


class ExperimentVersionOut(BaseModel):
    artifact_refs: list[UUID] | None = Field(None, title='Artifact Refs')
    artifact_version_refs: list[UUID] | None = Field(
        None, title='Artifact Version Refs'
    )
    as_of: AwareDatetime = Field(..., title='As Of')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    excludes: dict[str, Any] | None = Field(None, title='Excludes')
    execution_record_refs: list[str] | None = Field(None, title='Execution Record Refs')
    experiment_id: UUID = Field(..., title='Experiment Id')
    id: UUID = Field(..., title='Id')
    label: str | None = Field(None, title='Label')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    run_refs: list[UUID] | None = Field(None, title='Run Refs')
    version: int = Field(..., title='Version')


class ExportPoint(BaseModel):
    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    id: int = Field(..., title='Id')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime = Field(..., title='Wall Clock')


class Code(RootModel[str]):
    root: str = Field(..., max_length=512, title='Code')


class State(RootModel[str]):
    root: str = Field(..., max_length=2048, title='State')


class GitHubInstallationClaim(BaseModel):
    """
    Post-install redirect claim: GitHub sends
    ?installation_id=...&state=...&code=... back to the Integrations page (Setup
    URL), which POSTs all three here.

    `state` is the signed token the install_url carried (team identity).
    `code` is the user-authorization code GitHub adds when the App has
    "Request user authorization (OAuth) during installation" enabled --
    exchanged server-side to prove the claiming user ADMINISTERS the
    installation (review F1: state alone cannot; installation ids are small
    integers and the App-JWT lookup proves existence, never ownership).
    Absent state is a POLICY rejection (422) except for the same-team
    revival/re-claim path; absent code is a 422 when the server has the App's
    OAuth client creds configured.
    """

    code: Code | None = Field(None, title='Code')
    installation_id: int = Field(..., ge=1, title='Installation Id')
    state: State | None = Field(None, title='State')


class GitHubInstallationOut(BaseModel):
    account_login: str = Field(..., title='Account Login')
    installation_id: int = Field(..., title='Installation Id')
    repository_selection: str = Field(..., title='Repository Selection')
    suspended: bool = Field(..., title='Suspended')


class GitHubIntegrationState(StrEnum):
    """
    Server-side integration state the Integrations page renders.
    """

    not_configured = 'not_configured'
    available = 'available'
    installed = 'installed'


class Grant(StrEnum):
    """
    What ONE browser approval authorizes.

    A grant is a CAPABILITY, not a scope. `probe setup` asks for a set of them so
    the human approves once and the consent screen shows every capability
    together, instead of three separate round-trips each showing a fragment.

    The distinction matters most for CAPTURE. Scopes describe what an API caller
    may do to research data; they cannot express "stream this machine's prompts,
    file contents and tool output off the device". Rendering that as `read` on a
    consent screen would actively misdescribe it, so it gets its own name.
    """

    api = 'api'
    mcp = 'mcp'
    capture = 'capture'


class IndexCorpus(StrEnum):
    """
    The /v1/search corpus filter vocabulary (github.* and claude_code
    transcript docs are engine-native, not custom-ingest projections).
    """

    experiments = 'experiments'
    files = 'files'
    github = 'github'
    transcripts = 'transcripts'


class IngestArtifact(BaseModel):
    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    external_span_key: str | None = Field(None, title='External Span Key')
    external_span_type: str | None = Field(None, title='External Span Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    step_index: int | None = Field(None, title='Step Index')
    uri: str | None = Field(None, title='Uri')


class InstallationCaptureOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    device_id: str = Field(..., title='Device Id')
    hostname: str | None = Field(None, title='Hostname')
    label: str | None = Field(None, title='Label')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    os: str | None = Field(None, title='Os')
    source: str = Field(..., title='Source')


class InstallationCredentialOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    id: UUID = Field(..., title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    role: Role1 = Field(..., title='Role')
    scopes: list[str] | None = Field(None, title='Scopes')
    token_prefix: str = Field(..., title='Token Prefix')


class Role3(StrEnum):
    admin = 'admin'
    member = 'member'


class InviteCreate(BaseModel):
    email: str = Field(
        ..., max_length=254, pattern='^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$', title='Email'
    )
    role: Role3 | None = Field('member', title='Role')


class InviteOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    email: str = Field(..., title='Email')
    id: UUID = Field(..., title='Id')
    role: Role3 = Field(..., title='Role')


class LatestScalarOut(BaseModel):
    """
    One series' scalar summary: its endpoint value + extent, no point scan.
    """

    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    last_step_index: int | None = Field(None, title='Last Step Index')
    last_value: float | None = Field(None, title='Last Value')
    last_wall_clock: AwareDatetime | None = Field(None, title='Last Wall Clock')
    max_value: float | None = Field(None, title='Max Value')
    min_value: float | None = Field(None, title='Min Value')
    point_count: int = Field(..., title='Point Count')
    run_id: UUID = Field(..., title='Run Id')
    x_axis: str | None = Field('step', title='X Axis')


class Keys(RootModel[list[str]]):
    root: list[str] = Field(..., max_length=200, title='Keys')


class LatestScalarsRequest(BaseModel):
    """
    Cross-run scalar SUMMARY read — the foundation for run-table sort/filter by a
    final metric value (the MLflow `latest_metrics` / wandb Summary analog). Reads the
    derived `metric_series` catalog (which already holds last/min/max per series), so
    it never scans raw points.
    """

    keys: Keys | None = Field(None, title='Keys')
    kind: str | None = Field(None, title='Kind')
    run_ids: list[UUID] = Field(..., max_length=50, min_length=1, title='Run Ids')


class LatestScalarsResult(BaseModel):
    scalars: list[LatestScalarOut] = Field(..., title='Scalars')


class LineageEdgeOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    id: UUID = Field(..., title='Id')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    relation: str = Field(..., title='Relation')
    source_id: UUID = Field(..., title='Source Id')
    source_type: str = Field(..., title='Source Type')
    target_id: UUID = Field(..., title='Target Id')
    target_type: str = Field(..., title='Target Type')


class LineageEntityType(StrEnum):
    """
    The endpoints a lineage edge can connect (closed set).
    """

    run = 'run'
    artifact = 'artifact'
    artifact_version = 'artifact_version'


class LineageRelation(StrEnum):
    """
    The closed relation vocabulary.
    """

    consumes = 'consumes'
    produces = 'produces'
    evaluates_on = 'evaluates_on'
    forked_from = 'forked_from'
    resumed_from = 'resumed_from'
    promoted_to = 'promoted_to'
    derived_from = 'derived_from'


class MetricExportResult(BaseModel):
    """
    Lossless, paginated raw-point export (item 5): every point exactly once, NO
    downsampling for a stable committed dataset — the faithful-export counterpart to
    /series/query. Cursor on the stable metric_points id; pass `next_after_id` back as
    `after_id` for the next page (null means the last currently visible page).
    """

    next_after_id: int | None = Field(None, title='Next After Id')
    points: list[ExportPoint] = Field(..., title='Points')


class MetricInsertResult(BaseModel):
    deduped: int | None = Field(0, title='Deduped')
    inserted: int = Field(..., title='Inserted')
    series_count: int | None = Field(None, title='Series Count')


class MetricPointIn(BaseModel):
    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    key: str = Field(..., title='Key')
    kind: str | None = Field('model', title='Kind')
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime | None = Field(None, title='Wall Clock')


class MetricPointOut(BaseModel):
    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    id: int = Field(..., title='Id')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    run_id: UUID = Field(..., title='Run Id')
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime = Field(..., title='Wall Clock')


class MetricSeriesOut(BaseModel):
    """
    One catalog row: what/how-much/what-shape, no point scan (D15).
    """

    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    first_step_index: int | None = Field(None, title='First Step Index')
    first_wall_clock: AwareDatetime | None = Field(None, title='First Wall Clock')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    last_step_index: int | None = Field(None, title='Last Step Index')
    last_value: float | None = Field(None, title='Last Value')
    last_wall_clock: AwareDatetime | None = Field(None, title='Last Wall Clock')
    max_value: float | None = Field(None, title='Max Value')
    min_value: float | None = Field(None, title='Min Value')
    point_count: int = Field(..., title='Point Count')
    run_id: UUID = Field(..., title='Run Id')
    x_axis: str | None = Field('step', title='X Axis')


class Hostname(RootModel[str]):
    root: str = Field(..., max_length=256, title='Hostname')


class Os(RootModel[str]):
    root: str = Field(..., max_length=64, title='Os')


class PairRequest(BaseModel):
    hostname: Hostname | None = Field(None, title='Hostname')
    os: Os | None = Field(None, title='Os')
    pairing_token: str = Field(..., min_length=1, title='Pairing Token')


class PairResponse(BaseModel):
    customer_id: str = Field(..., title='Customer Id')
    device_id: str = Field(..., title='Device Id')
    device_token: str = Field(..., title='Device Token')


class PairingTokenRequest(BaseModel):
    source: str | None = Field('claude_code', title='Source')


class PairingTokenResponse(BaseModel):
    expires_in_seconds: int = Field(..., title='Expires In Seconds')
    pairing_token: str = Field(..., title='Pairing Token')


class ParentRelation(StrEnum):
    fork = 'fork'
    resume = 'resume'
    retry = 'retry'
    branch = 'branch'


class PendingInviteOut(BaseModel):
    """
    An invite shown to the invitee on /onboarding (joined to team name).
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    display_name: str = Field(..., title='Display Name')
    id: UUID = Field(..., title='Id')
    role: Role3 = Field(..., title='Role')


class PinnedExperiment(BaseModel):
    experiment_id: UUID = Field(..., title='Experiment Id')
    experiment_name: str = Field(..., title='Experiment Name')


class PinnedProject(BaseModel):
    experiments: list[PinnedExperiment] | None = Field(None, title='Experiments')
    project_id: UUID = Field(..., title='Project Id')
    project_name: str = Field(..., title='Project Name')


class ProjectArtifactCreate(BaseModel):
    """
    Project-anchored artifact (fold #22); same shape as the experiment-anchored one.
    """

    content_hash: str | None = Field(None, title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    is_reference: bool | None = Field(False, title='Is Reference')
    kind: str | None = Field('file', title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    uri: str | None = Field(None, title='Uri')


class ProjectCreate(BaseModel):
    description: str | None = Field(None, title='Description')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')
    workspace_id: UUID | None = Field(None, title='Workspace Id')


class ProjectOut(BaseModel):
    archived_at: AwareDatetime | None = Field(None, title='Archived At')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    description: str | None = Field(None, title='Description')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    slug: str = Field(..., title='Slug')
    updated_at: AwareDatetime = Field(..., title='Updated At')
    workspace_id: UUID | None = Field(..., title='Workspace Id')


class ProjectPatch(BaseModel):
    """
    Field-replace PATCH (D9). Only provided fields change; None = untouched.

    `workspace_id` re-files the project into another workspace (D6: projects
    stay re-fileable); it is resolved in-tenant before use (amendment #3).
    """

    description: str | None = Field(None, title='Description')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: Name | None = Field(None, title='Name')
    workspace_id: UUID | None = Field(None, title='Workspace Id')


class RunCounts(BaseModel):
    """
    Child-row tallies nested under RunOut.counts (dashboard contract).
    """

    artifacts: int = Field(..., title='Artifacts')
    metrics: int = Field(..., title='Metrics')
    spans: int = Field(..., title='Spans')


class RunCreate(BaseModel):
    config: dict[str, Any] | None = Field(None, title='Config')
    env_ref: str | None = Field(None, title='Env Ref')
    external_id: str | None = Field(None, title='External Id')
    foreign_keys: dict[str, Any] | None = Field(None, title='Foreign Keys')
    group_id: UUID | None = Field(None, title='Group Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_relation: ParentRelation | None = None
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    source: str | None = Field('api', title='Source')
    tags: list[str] | None = Field(None, title='Tags')


class RunIds(RootModel[list[UUID]]):
    root: list[UUID] = Field(..., max_length=50, title='Run Ids')


class RunGcRequest(BaseModel):
    """
    Permanently purge deleted runs (owner/admin). Exactly one selector: an
    explicit id list, or every run soft-deleted before `older_than`.
    """

    older_than: AwareDatetime | None = Field(None, title='Older Than')
    run_ids: RunIds | None = Field(None, title='Run Ids')


class RunGcResult(BaseModel):
    purged: int = Field(..., title='Purged')


class RunGroupCreate(BaseModel):
    kind: str | None = Field('group', title='Kind')
    name: str = Field(..., title='Name')
    spec: dict[str, Any] | None = Field(None, title='Spec')


class RunGroupOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    experiment_id: UUID = Field(..., title='Experiment Id')
    id: UUID = Field(..., title='Id')
    kind: str = Field(..., title='Kind')
    name: str = Field(..., title='Name')
    spec: dict[str, Any] | None = Field(None, title='Spec')


class RunGroupPatch(BaseModel):
    """
    Field-replace PATCH (D9). Only provided fields change; None = untouched.
    """

    name: Name | None = Field(None, title='Name')
    spec: dict[str, Any] | None = Field(None, title='Spec')


class RunNode(BaseModel):
    alive: bool | None = Field(None, title='Alive')
    created_at: AwareDatetime = Field(..., title='Created At')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    short_id: str | None = Field(None, title='Short Id')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: str = Field(..., title='Status')


class RunSessionOut(BaseModel):
    """
    A coding-agent session that touched this run.

    Ordered by when we first saw it, so the first entry is the session the run
    originated in — the same one recorded in
    `runs.foreign_keys.<agent>_session_id`.

    `captured` is deliberately NOT here. Whether a transcript exists is the
    engine's answer, not this database's: capture is a per-device permission a
    user can switch off, so a recorded session with no transcript is an
    expected state. The run page resolves it against the transcripts corpus at
    render time and shows captured / pending / not-captured there. Asserting it
    here would mean this endpoint lying whenever the engine disagreed.
    """

    agent: str = Field(..., title='Agent')
    first_seen_at: AwareDatetime = Field(..., title='First Seen At')
    session_id: str = Field(..., title='Session Id')


class RunStatus(StrEnum):
    created = 'created'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    crashed = 'crashed'
    canceled = 'canceled'


class Scope(StrEnum):
    """
    Coarse v1 authorization scopes (D2). Narrowable later; checked as explicit
    sets per route, NOT as a hierarchy (a `write` token does not imply `read`).
    """

    read = 'read'
    write = 'write'
    delete = 'delete'
    admin = 'admin'


class ScopedUploadRequest(BaseModel):
    """
    Upload fields shared by project and experiment anchors.

    The anchor comes exclusively from the URL and the R2 pointer/key are always
    server-built. Forbid extras so a client-supplied ``uri`` or ``key`` is rejected
    instead of being silently ignored by Pydantic.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    content_hash: str = Field(..., title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')


class SearchEntityType(StrEnum):
    """
    Entities the exact SQL channel searches (names + slugs).
    """

    project = 'project'
    experiment = 'experiment'
    artifact = 'artifact'


class SearchRequest(BaseModel):
    corpus: list[IndexCorpus] | None = Field(None, title='Corpus')
    exact_cursor: str | None = Field(None, title='Exact Cursor')
    exact_limit: int | None = Field(20, ge=1, le=50, title='Exact Limit')
    include_semantic: bool | None = Field(True, title='Include Semantic')
    project_id: UUID | None = Field(None, title='Project Id')
    query: str = Field(..., max_length=500, min_length=1, title='Query')
    semantic_cursor: str | None = Field(None, title='Semantic Cursor')
    top_k: int | None = Field(20, ge=1, le=50, title='Top K')
    workspace_id: UUID | None = Field(None, title='Workspace Id')


class SearchState(StrEnum):
    ok = 'ok'
    partial = 'partial'


class SemanticChunk(BaseModel):
    """
    One MATCHED chunk of a document, full content.

    Not truncated to a fixed cap: when the response must shrink, the budget
    drops whole chunks from the tail rather than clipping every chunk into
    uselessness. `graph_evidence` is empty for a text-only match, so its
    absence is itself signal.
    """

    chunk_id: str | None = Field(None, title='Chunk Id')
    content: str = Field(..., title='Content')
    graph_evidence: list[dict[str, Any]] | None = Field(None, title='Graph Evidence')
    score: float = Field(..., title='Score')
    why_relevant: str | None = Field(None, title='Why Relevant')


class SemanticRefKind(StrEnum):
    """
    research-os entities a semantic doc id resolves back to.
    """

    run = 'run'
    experiment = 'experiment'
    file = 'file'


class SeriesPoint(BaseModel):
    smoothed: float | None = Field(None, title='Smoothed')
    step_index: int | None = Field(None, title='Step Index')
    value: float = Field(..., title='Value')
    wall_clock: AwareDatetime = Field(..., title='Wall Clock')


class MaxPoints(RootModel[int]):
    root: int = Field(..., ge=2, le=100000, title='Max Points')


class Smoothing(StrEnum):
    ema = 'ema'
    sma = 'sma'


class SeriesResult(BaseModel):
    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    points: list[SeriesPoint] = Field(..., title='Points')
    run_id: UUID = Field(..., title='Run Id')
    x_axis: str = Field(..., title='X Axis')


class SeriesSelector(BaseModel):
    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')


class SpanCreate(BaseModel):
    attributes: dict[str, Any] | None = Field(None, title='Attributes')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    env_ref: str | None = Field(None, title='Env Ref')
    external_key: str | None = Field(None, title='External Key')
    id: UUID = Field(..., title='Id')
    name: str | None = Field(None, title='Name')
    parent_span_id: UUID | None = Field(None, title='Parent Span Id')
    provider: str | None = Field(None, title='Provider')
    span_type: str = Field(..., title='Span Type')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: str | None = Field('running', title='Status')
    step_index: int | None = Field(None, title='Step Index')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SpanOut(BaseModel):
    attributes: dict[str, Any] | None = Field(None, title='Attributes')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    external_key: str | None = Field(None, title='External Key')
    id: UUID = Field(..., title='Id')
    name: str | None = Field(None, title='Name')
    parent_span_id: UUID | None = Field(None, title='Parent Span Id')
    provider: str | None = Field(None, title='Provider')
    run_id: UUID = Field(..., title='Run Id')
    span_type: str = Field(..., title='Span Type')
    started_at: AwareDatetime = Field(..., title='Started At')
    status: str = Field(..., title='Status')
    step_index: int | None = Field(None, title='Step Index')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SpanTypeCount(BaseModel):
    count: int = Field(..., title='Count')
    span_type: str = Field(..., title='Span Type')


class SpanUpsertResult(BaseModel):
    """
    Typed replacement for the bare `{"upserted": n}` dict (D9).
    """

    upserted: int = Field(..., title='Upserted')


class StaleClientOut(BaseModel):
    """
    One known, stale client included in the dashboard decision.
    """

    current: str = Field(..., title='Current')
    kind: ClientKind
    latest: str = Field(..., title='Latest')
    min: str | None = Field(..., title='Min')
    status: ClientUpdateStatus


class StandaloneCredentialOut(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    id: UUID = Field(..., title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    name: str = Field(..., title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    token_prefix: str = Field(..., title='Token Prefix')


class StepCreate(BaseModel):
    attributes: dict[str, Any] | None = Field(None, title='Attributes')
    name: str | None = Field(None, title='Name')
    step_index: int = Field(..., title='Step Index')
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SummaryState(StrEnum):
    """
    Derived UI state for a summary (badge).
    """

    fresh = 'fresh'
    generating = 'generating'
    stale = 'stale'
    failed = 'failed'


class SummaryStatusOut(BaseModel):
    anchor_id: UUID = Field(..., title='Anchor Id')
    anchor_type: AnchorType
    attempts: int = Field(..., title='Attempts')
    has_summary: bool = Field(..., title='Has Summary')
    state: SummaryState
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class SwitchTeamRequest(BaseModel):
    customer_id: str = Field(..., title='Customer Id')


class TeamCreate(BaseModel):
    """
    POST /auth/teams. `slug` format/uniqueness is validated
    server-side (app.teams.service) so the 400/409 carries a helpful message +
    a collision suggestion; the model only bounds length.
    """

    display_name: str = Field(..., max_length=120, min_length=1, title='Display Name')
    slug: str = Field(..., max_length=64, min_length=1, title='Slug')


class Role6(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class TeamMemberOut(BaseModel):
    """
    One active team membership joined to its human identity.
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    email: str = Field(..., title='Email')
    name: str | None = Field(None, title='Name')
    picture: str | None = Field(None, title='Picture')
    role: Role6 = Field(..., title='Role')
    user_id: UUID = Field(..., title='User Id')


class Role7(StrEnum):
    admin = 'admin'
    member = 'member'


class TeamMemberRoleUpdate(BaseModel):
    """
    Owner-controlled role change for an existing non-owner member.

    Ownership transfer is intentionally not part of the v1 management surface;
    a team always retains the owner created during provisioning.
    """

    role: Role7 = Field(..., title='Role')


class Role8(StrEnum):
    owner = 'owner'
    admin = 'admin'
    member = 'member'


class TeamOut(BaseModel):
    customer_id: str = Field(..., title='Customer Id')
    display_name: str | None = Field(None, title='Display Name')
    role: Role8 = Field(..., title='Role')


class TokenCreate(BaseModel):
    """
    POST /v1/tokens (session-only mint). `scopes=None` inherits the caller's
    role; e.g. `['read']` mints a read-only 'notebook' token. `expires_at=None`
    means non-expiring (house precedent).
    """

    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    name: str = Field(..., max_length=120, min_length=1, title='Name')
    scopes: list[Scope] | None = Field(None, title='Scopes')


class TokenCreated(BaseModel):
    """
    Mint response — carries the plaintext secret ONCE (never stored, never
    shown again).
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    id: UUID = Field(..., title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    name: str = Field(..., title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    token: str = Field(..., title='Token')
    token_prefix: str = Field(..., title='Token Prefix')


class TokenOut(BaseModel):
    """
    A token as listed (never carries the secret).
    """

    created_at: AwareDatetime = Field(..., title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    id: UUID = Field(..., title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    name: str = Field(..., title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    token_prefix: str = Field(..., title='Token Prefix')


class UploadGcRequest(BaseModel):
    older_than: AwareDatetime = Field(..., title='Older Than')


class UploadGcResult(BaseModel):
    swept: int = Field(..., title='Swept')


class UploadRequest(BaseModel):
    content_hash: str = Field(..., title='Content Hash')
    content_type: str | None = Field(None, title='Content Type')
    kind: str | None = Field(None, title='Kind')
    meta: dict[str, Any] | None = Field(None, title='Meta')
    name: str = Field(..., title='Name')
    size_bytes: int | None = Field(None, title='Size Bytes')
    span_id: UUID | None = Field(None, title='Span Id')
    step_index: int | None = Field(None, title='Step Index')


class UploadResponse(BaseModel):
    artifact_id: UUID = Field(..., title='Artifact Id')
    have: bool = Field(..., title='Have')
    key: str | None = Field(None, title='Key')
    upload_headers: dict[str, str] | None = Field(None, title='Upload Headers')
    upload_url: str | None = Field(None, title='Upload Url')


class ValidationError(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class VersionPair(BaseModel):
    latest: str | None = Field(None, title='Latest')
    min: str | None = Field(None, title='Min')


class WideColumn(BaseModel):
    """
    One column of a wide (step-indexed) metric table: a distinct series.
    """

    dimensions: dict[str, Any] | None = Field(None, title='Dimensions')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')


class WideRow(BaseModel):
    step_index: int = Field(..., title='Step Index')
    values: list[float | None] = Field(..., title='Values')


class WideSeriesResult(BaseModel):
    """
    Step x metric table (item 4): the pivot clients would otherwise do by hand,
    aligned by step_index. Only STEPPED points participate; wall-clock-only series are
    read via the long endpoints. Bounded to `max_rows` steps — `next_step` pages the
    remainder by passing it back as `step_from`.
    """

    columns: list[WideColumn] = Field(..., title='Columns')
    next_step: int | None = Field(None, title='Next Step')
    rows: list[WideRow] = Field(..., title='Rows')
    truncated: bool | None = Field(False, title='Truncated')


class WorkspaceKind(StrEnum):
    """
    The closed workspace kind vocabulary (mirrors the DB CHECK).

    `SHARED` is RETIRED (decision 2026-07-16): app code never creates a shared
    workspace anymore. It is kept here only so the API can still serialize a
    legacy null-owner shared row on an existing install until it is retired by
    `app.workspaces.retire_shared` and a future contract migration drops the kind.
    """

    personal = 'personal'
    shared = 'shared'


class WorkspaceOut(BaseModel):
    """
    One dropdown entry: the dashboard's workspace switcher builds on this.
    """

    archived_at: AwareDatetime | None = Field(None, title='Archived At')
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    id: UUID = Field(..., title='Id')
    kind: WorkspaceKind
    name: str = Field(..., title='Name')
    owner_user_id: str | None = Field(None, title='Owner User Id')
    project_count: int | None = Field(0, title='Project Count')
    slug: str = Field(..., title='Slug')


class WorkspacePatch(BaseModel):
    """
    The one user-editable workspace field.

    Slugs and ownership are stable server-managed identity. Names are display
    labels, trimmed at the API boundary so whitespace-only values never reach
    the database.
    """

    name: str = Field(..., max_length=120, min_length=1, title='Name')


class ArtifactPinImpact(BaseModel):
    """
    What a delete would break (D7): the actual projects and experiments whose
    manifests or lineage edges pin one of this artifact's versions.
    """

    artifact_id: UUID = Field(..., title='Artifact Id')
    pinned: bool = Field(..., title='Pinned')
    projects: list[PinnedProject] | None = Field(None, title='Projects')


class CapabilityRegistrationOut(BaseModel):
    capabilities: ClientCapabilitiesOut
    installation_id: UUID = Field(..., title='Installation Id')


class ClientInstallationOut(BaseModel):
    capabilities: ClientCapabilitiesOut | None = None
    capture: InstallationCaptureOut | None = None
    created_at: AwareDatetime = Field(..., title='Created At')
    credentials: list[InstallationCredentialOut] = Field(..., title='Credentials')
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class ClientInstallationsOut(BaseModel):
    installations: list[ClientInstallationOut] = Field(..., title='Installations')
    standalone_captures: list[InstallationCaptureOut] = Field(
        ..., title='Standalone Captures'
    )
    standalone_credentials: list[StandaloneCredentialOut] = Field(
        ..., title='Standalone Credentials'
    )


class ClientStatusOut(BaseModel):
    """
    Server-side update-banner decision for the authenticated user.
    """

    advisory: str | None = Field(None, title='Advisory')
    clients: list[StaleClientOut] | None = Field(None, title='Clients')
    severity: ClientUpdateStatus | None = None
    update_available: bool | None = Field(False, title='Update Available')


class ClientVersionOut(BaseModel):
    advisory: str | None = Field(None, title='Advisory')
    cli: VersionPair | None = Field({}, validate_default=True)
    plugin: VersionPair | None = Field({}, validate_default=True)


class Scopes(RootModel[list[Scope]]):
    root: list[Scope] = Field(..., min_length=1, title='Scopes')


class DeviceAuthorizationStart(BaseModel):
    """
    Start a first-party CLI browser handoff.

    PKCE is mandatory even though the high-entropy device code is already a
    bearer secret: it binds the exchange to the CLI process that initiated it
    if a terminal transcript or launch URL is copied elsewhere.
    """

    code_challenge: str = Field(
        ..., pattern='^[A-Za-z0-9_-]{43}$', title='Code Challenge'
    )
    grants: list[Grant] | None = Field(None, min_length=1, title='Grants')
    scopes: Scopes | None = Field(None, title='Scopes')
    token_name: str | None = Field(
        'Research OS CLI', max_length=120, min_length=1, title='Token Name'
    )


class DeviceGrantOut(BaseModel):
    """
    One credential minted by an approval. `token` is plaintext, delivered ONCE.
    """

    device_id: str | None = Field(None, title='Device Id')
    grant: Grant
    token: str = Field(..., title='Token')
    token_id: UUID | None = Field(None, title='Token Id')


class DeviceTokenCreated(BaseModel):
    """
    Exchange result.

    The inherited top-level fields carry the `api` PAT exactly as they always
    have. That shape is FROZEN: older CLIs send no `grants`, get `{api}`, and
    must see a byte-identical response.

    `grants` carries every credential the approval minted, including the api PAT
    again, so a client that asked for a set does not have to special-case which
    one landed on top.
    """

    created_at: AwareDatetime | None = Field(None, title='Created At')
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    grants: list[DeviceGrantOut] | None = Field(None, title='Grants')
    id: UUID | None = Field(None, title='Id')
    last_used_at: AwareDatetime | None = Field(None, title='Last Used At')
    name: str | None = Field(None, title='Name')
    scopes: list[str] | None = Field(None, title='Scopes')
    token: str | None = Field(None, title='Token')
    token_prefix: str | None = Field(None, title='Token Prefix')
    token_type: Literal['Bearer'] = Field('Bearer', title='Token Type')


class EdgeCreate(BaseModel):
    meta: dict[str, Any] | None = Field(None, title='Meta')
    relation: LineageRelation
    source_id: UUID = Field(..., title='Source Id')
    source_type: LineageEntityType
    target_id: UUID = Field(..., title='Target Id')
    target_type: LineageEntityType


class ExactHit(BaseModel):
    entity_type: SearchEntityType
    experiment_id: UUID | None = Field(None, title='Experiment Id')
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    project_id: UUID | None = Field(None, title='Project Id')
    run_id: UUID | None = Field(None, title='Run Id')
    score: float = Field(..., title='Score')
    shared_folder_id: UUID | None = Field(None, title='Shared Folder Id')
    slug: str | None = Field(None, title='Slug')
    workspace_id: UUID | None = Field(None, title='Workspace Id')


class ExactSection(BaseModel):
    active_runs_count: int | None = Field(None, title='Active Runs Count')
    cursor: str | None = Field(None, title='Cursor')
    error: ChannelError | None = None
    results: list[ExactHit] | None = Field(None, title='Results')


class ExperimentNode(BaseModel):
    active_run_count: int | None = Field(0, title='Active Run Count')
    created_at: AwareDatetime = Field(..., title='Created At')
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    project_id: UUID = Field(..., title='Project Id')
    run_count: int | None = Field(0, title='Run Count')
    runs: list[RunNode] | None = Field(None, title='Runs')
    slug: str | None = Field(None, title='Slug')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class GitHubIntegrationOut(BaseModel):
    install_url: str | None = Field(..., title='Install Url')
    installations: list[GitHubInstallationOut] = Field(..., title='Installations')
    state: GitHubIntegrationState


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class IngestRun(BaseModel):
    config: dict[str, Any] | None = Field(None, title='Config')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    external_id: str = Field(..., title='External Id')
    foreign_keys: dict[str, Any] | None = Field(None, title='Foreign Keys')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_external_id: str | None = Field(None, title='Parent External Id')
    parent_relation: ParentRelation | None = None
    source: str | None = Field('api', title='Source')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: RunStatus | None = 'running'
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class IngestRunRequest(BaseModel):
    artifacts: list[IngestArtifact] | None = Field(
        None, max_length=1000, title='Artifacts'
    )
    batch_id: str | None = Field(None, title='Batch Id')
    execution_record: ExecutionRecordCreate | None = None
    experiment_hypothesis: str | None = Field(None, title='Experiment Hypothesis')
    experiment_slug: str = Field(..., title='Experiment Slug')
    metrics: list[MetricPointIn] | None = Field(None, max_length=50000, title='Metrics')
    project_slug: str | None = Field(None, title='Project Slug')
    run: IngestRun
    spans: list[SpanCreate] | None = Field(None, max_length=10000, title='Spans')


class MetricBatch(BaseModel):
    points: list[MetricPointIn] = Field(..., max_length=50000, title='Points')


class ProjectNode(BaseModel):
    active_run_count: int | None = Field(0, title='Active Run Count')
    created_at: AwareDatetime = Field(..., title='Created At')
    experiment_count: int | None = Field(0, title='Experiment Count')
    experiments: list[ExperimentNode] | None = Field(None, title='Experiments')
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    slug: str | None = Field(None, title='Slug')
    updated_at: AwareDatetime = Field(..., title='Updated At')
    workspace_id: UUID | None = Field(None, title='Workspace Id')


class RunDetailOut(BaseModel):
    """
    The /v1 read view of a run: RunOut plus the fold fields that are DELIBERATELY
    absent from RunOut so the frozen ingest response stays byte-identical (the ingest
    route keeps response_model=RunOut, which filters these out). short_id (fold #21)
    is the human-facing petname the dashboard displays; created_by (fold #1), env_ref
    (fold #7), and foreign_keys (fold #8) surface here for reads.
    """

    config: dict[str, Any] | None = Field(None, title='Config')
    counts: RunCounts | None = None
    created_at: AwareDatetime = Field(..., title='Created At')
    created_by: str | None = Field(None, title='Created By')
    customer_id: str = Field(..., title='Customer Id')
    deleted_at: AwareDatetime | None = Field(None, title='Deleted At')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    env_ref: str | None = Field(None, title='Env Ref')
    experiment_id: UUID = Field(..., title='Experiment Id')
    external_id: str | None = Field(None, title='External Id')
    foreign_keys: dict[str, Any] | None = Field(None, title='Foreign Keys')
    group_id: UUID | None = Field(None, title='Group Id')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_relation: ParentRelation | None = None
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    short_id: str | None = Field(None, title='Short Id')
    source: str = Field(..., title='Source')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: RunStatus
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class RunLineage(BaseModel):
    """
    Ancestors + descendants of a run (recursive-CTE result).
    """

    ancestors: list[RunDetailOut] | None = Field(None, title='Ancestors')
    descendants: list[RunDetailOut] | None = Field(None, title='Descendants')
    run_id: UUID = Field(..., title='Run Id')


class RunOut(BaseModel):
    config: dict[str, Any] | None = Field(None, title='Config')
    counts: RunCounts | None = None
    created_at: AwareDatetime = Field(..., title='Created At')
    customer_id: str = Field(..., title='Customer Id')
    deleted_at: AwareDatetime | None = Field(None, title='Deleted At')
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    experiment_id: UUID = Field(..., title='Experiment Id')
    external_id: str | None = Field(None, title='External Id')
    group_id: UUID | None = Field(None, title='Group Id')
    id: UUID = Field(..., title='Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: str = Field(..., title='Name')
    parent_relation: ParentRelation | None = None
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    source: str = Field(..., title='Source')
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: RunStatus
    summary: dict[str, Any] | None = Field(None, title='Summary')
    tags: list[str] | None = Field(None, title='Tags')


class RunPatch(BaseModel):
    ended_at: AwareDatetime | None = Field(None, title='Ended At')
    env_ref: str | None = Field(None, title='Env Ref')
    foreign_keys: dict[str, Any] | None = Field(None, title='Foreign Keys')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    name: Name | None = Field(None, title='Name')
    status: RunStatus | None = None
    summary: dict[str, Any] | None = Field(None, title='Summary')


class SemanticRef(BaseModel):
    id: UUID = Field(..., title='Id')
    kind: SemanticRefKind


class Series(RootModel[list[SeriesSelector]]):
    root: list[SeriesSelector] = Field(..., max_length=200, title='Series')


class SeriesQueryRequest(BaseModel):
    """
    Multi-run, multi-series read for the run page AND N-run comparison (D9).
    """

    max_points: MaxPoints | None = Field(None, title='Max Points')
    run_ids: list[UUID] = Field(..., max_length=50, min_length=1, title='Run Ids')
    series: Series | None = Field(None, title='Series')
    smoothing: Smoothing | None = Field(None, title='Smoothing')
    smoothing_factor: float | None = Field(
        0.6, ge=0.0, lt=1.0, title='Smoothing Factor'
    )
    smoothing_window: int | None = Field(10, ge=1, le=5000, title='Smoothing Window')
    step_from: int | None = Field(None, title='Step From')
    step_to: int | None = Field(None, title='Step To')


class SeriesQueryResult(BaseModel):
    series: list[SeriesResult] = Field(..., title='Series')


class SpanBatch(BaseModel):
    spans: list[SpanCreate] = Field(..., max_length=10000, title='Spans')


class BrowseResponse(BaseModel):
    cursor: str | None = Field(None, title='Cursor')
    depth: int | None = Field(1, title='Depth')
    experiments: list[ExperimentNode] | None = Field(None, title='Experiments')
    limit: int | None = Field(50, title='Limit')
    projects: list[ProjectNode] | None = Field(None, title='Projects')
    runs: list[RunNode] | None = Field(None, title='Runs')
    truncated: bool | None = Field(False, title='Truncated')


class RunBundle(BaseModel):
    """
    One request: run + coding sessions + catalog + artifact index (bounded) +
    spans overview + lineage refs. Raw points are excluded (fetch via
    /series/query).
    """

    artifact_total: int = Field(..., title='Artifact Total')
    artifacts: list[ArtifactOut] = Field(..., title='Artifacts')
    child_run_ids: list[UUID] | None = Field(None, title='Child Run Ids')
    parent_run_id: UUID | None = Field(None, title='Parent Run Id')
    run: RunDetailOut
    series: list[MetricSeriesOut] = Field(..., title='Series')
    sessions: list[RunSessionOut] | None = Field(None, title='Sessions')
    span_types: list[SpanTypeCount] = Field(..., title='Span Types')


class SemanticHit(BaseModel):
    chunks: list[SemanticChunk] | None = Field(None, title='Chunks')
    doc_id: str = Field(..., title='Doc Id')
    matched_via: list[dict[str, Any]] | None = Field(None, title='Matched Via')
    ref: SemanticRef | None = None
    score: float = Field(..., title='Score')
    snippet: str = Field(..., title='Snippet')
    source_system: str | None = Field(None, title='Source System')
    source_url: str | None = Field(None, title='Source Url')
    title: str | None = Field(None, title='Title')


class SemanticSection(BaseModel):
    confidence_breakdown: dict[str, int] | None = Field(
        None, title='Confidence Breakdown'
    )
    cursor: str | None = Field(None, title='Cursor')
    dropped_chunk_count: int | None = Field(0, title='Dropped Chunk Count')
    dropped_result_count: int | None = Field(0, title='Dropped Result Count')
    error: ChannelError | None = None
    results: list[SemanticHit] | None = Field(None, title='Results')
    stripped_graph_evidence_count: int | None = Field(
        0, title='Stripped Graph Evidence Count'
    )
    total_candidates: int | None = Field(None, title='Total Candidates')


class SearchResponse(BaseModel):
    dropped_chunk_count: int | None = Field(0, title='Dropped Chunk Count')
    dropped_result_count: int | None = Field(0, title='Dropped Result Count')
    exact: ExactSection
    project_id: UUID | None = Field(None, title='Project Id')
    query: str = Field(..., title='Query')
    semantic: SemanticSection
    state: SearchState
    truncated: bool | None = Field(False, title='Truncated')
