#!/usr/bin/env python
"""Regenerate the typed client models from the backend's OpenAPI schema.

Reads ``schema/openapi.json`` (a snapshot of research-os's FastAPI schema) and
writes ``src/ros/_generated/models.py``. The generated file is the "floor" the
hand-written SDK ergonomics sit on. Never hand-edit the generated file; when the
contract moves, refresh ``schema/openapi.json`` (see ``scripts/dump_openapi.py``)
and re-run this.

    python scripts/gen_models.py

Requires the dev extra (`pip install -e ".[dev]"`), which pulls
``datamodel-code-generator``.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schema" / "openapi.json"
OUT = ROOT / "src" / "ros" / "_generated" / "models.py"


def main() -> int:
    if not SCHEMA.exists():
        print(f"missing {SCHEMA}; run scripts/dump_openapi.py first", file=sys.stderr)
        return 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(SCHEMA),
        "--input-file-type",
        "openapi",
        "--output",
        str(OUT),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.11",
        "--use-standard-collections",
        "--use-union-operator",
        "--use-schema-description",
        "--field-constraints",
        "--collapse-root-models",
        "--disable-timestamp",
        "--custom-file-header",
        "# GENERATED by scripts/gen_models.py from schema/openapi.json. Do not edit.",
    ]
    print(" ".join(cmd))
    proc = subprocess.run(cmd)
    if proc.returncode == 0:
        print(f"wrote {OUT.relative_to(ROOT)}")
    return proc.returncode


if __name__ == "__main__":
    raise SystemExit(main())
